apiVersion: v1
kind: Service
metadata:
  name: {{ include "bhudristi-backend.fullname" . }}-api
  labels:
    {{- include "bhudristi-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "bhudristi-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
